-- 1 > DDL
-- Trong file cafedev_database_bt1
-- 1.1 Tao quan he
-- Trong file cafedev_database_bt1
-- 1.2 
alter table SANPHAM add GHICHU varchar(20)
-- 1.3
alter table KHACHHANG add LOAIKH tinyint
-- 1.4
alter table SANPHAM alter column GHICHU varchar(100)
-- 1.5
alter table SANPHAM drop column GHICHU
-- 1.6
alter table KHACHHANG alter column LOAIKH varchar(20)
-- 1.7
alter table SANPHAM add constraint C_DVT check(DVT='cay' OR DVT='hop' OR DVT='cai' OR DVT='quyen' OR DVT='chuc')
-- 1.8
alter table CTHD alter column SOHD int NOT NULL
alter table CTHD alter column MASP char(4) NOT NULL
alter table CTHD add constraint PRI_CTHD primary key (SOHD,MASP)
alter table SANPHAM add constraint C_GIABAN check(GIA>=500)
-- 1.9 
alter table CTHD add constraint C_SLMUA check (SL>0)
-- 1.10
alter table KHACHHANG add constraint C_NGDK_NGSINH check(NGDK>NGSINH)

-- 2 > DML

-- 2.1 : Nhap du lieu cho quan he

-- 2.2 
SELECT * 
INTO SANPHAM1
FROM  SANPHAM

SELECT * 
INTO KHACHHANG1
FROM  KHACHHANG
-- 2.3
update SANPHAM1 
set GIA=GIA*1.05 
where NUOCSX='Thai Lan'
-- 2.4
update SANPHAM1 
set GIA=GIA*0.95 
where NUOCSX='Trung Quoc' AND GIA<=10000
-- 2.5
update KHACHHANG1 
set LOAIKH = 'Vip' 
where ( NGDK < '1/1/2007' AND DOANHSO >=10000000 ) OR ( NGDK >='1/1/2007' AND DOANHSO >= 2000000 )
-- 3 > NGON NGU TRUY VAN DU LIEU CO CAU TRUC

-- 3.1
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NUOCSX = 'Trung Quoc'
-- 3.2 
SELECT MASP , TENSP
FROM SANPHAM
WHERE DVT IN ('cay','quyen')
-- 3.3
select masp,tensp from SANPHAM where masp like 'B%01'
-- 3.4
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA BETWEEN 30000 AND 40000
-- 3.5
SELECT MASP,TENSP
FROM SANPHAM
WHERE (NUOCSX ='Trung Quoc' OR NUOCSX = 'Thai Lan') AND GIA BETWEEN 30000 AND 40000
-- 3.6
SELECT SOHD,TRIGIA
FROM HOADON
WHERE NGHD IN ('01/01/2007','02/01/2007')
-- 3.7
SELECT SOHD,TRIGIA , NGHD
FROM HOADON
WHERE YEAR(NGHD) = '2007' AND MONTH(NGHD) = '01'
ORDER BY NGHD ASC , TRIGIA DESC
--3.8
SELECT A.MAKH , HOTEN 
FROM KHACHHANG A, HOADON B
WHERE A.MAKH = B.MAKH AND NGHD = '1/1/2007'
-- 3.9
SELECT SOHD , TRIGIA 
FROM HOADON A , NHANVIEN B
WHERE A.MANV = B.MANV AND HOTEN = 'Nguyen Van B' AND NGHD = '10/28/2006'
-- 3.10
SELECT SANPHAM.MASP , TENSP
FROM (KHACHHANG JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH) JOIN ( SANPHAM JOIN CTHD ON SANPHAM.MASP = CTHD.MASP ) ON A.SOHD = B.SOHD
WHERE HOTEN = 'Nguyen Van A' AND MONTH(NGHD)= 10 AND YEAR(NGHD) = 2006
-- 3.11
SELECT DISTINCT SOHD 
FROM CTHD
WHERE MASP ='BB01' OR MASP = 'BB02'
-- 3.12
SELECT DISTINCT SOHD 
FROM CTHD
WHERE ( MASP ='BB01' OR MASP = 'BB02' ) AND SL BETWEEN 10 AND 20
-- 3.13
SELECT SOHD
FROM CTHD A
WHERE MASP = 'BB02' AND A.SL BETWEEN 10 AND 20 AND EXISTS (
	SELECT SOHD 
	FROM CTHD B
	WHERE MASP = 'BB01' AND A.SOHD = B.SOHD AND B.SL BETWEEN 10 AND 20
	)
-- 3.14
SELECT MASP , TENSP
FROM SANPHAM 
WHERE NUOCSX ='Trung Quoc'
UNION
SELECT SANPHAM.MASP , TENSP
FROM (HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NGHD = '1/1/2007'
-- 3.15
SELECT A.MASP , TENSP
FROM SANPHAM A
WHERE NOT EXISTS (
	SELECT MASP
	FROM CTHD B
	WHERE A.MASP = B.MASP
	)
-- 3.16
SELECT C.MASP , TENSP
FROM SANPHAM C
WHERE NOT EXISTS (
	SELECT MASP
	FROM CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
	WHERE C.MASP = CTHD.MASP AND YEAR(HOADON.NGHD) = 2006
	) 
-- 3.17
SELECT C.MASP , TENSP
FROM SANPHAM C
WHERE NUOCSX = 'Trung Quoc' AND NOT EXISTS (
	SELECT MASP
	FROM CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
	WHERE C.MASP = CTHD.MASP AND YEAR(HOADON.NGHD) = 2006
	) 
-- 3.18
select SOHD
from HOADON 
where not exists ( 
			select MASP
			from SANPHAM
			where nuocsx= 'Singapore' and not exists (
				select SOHD
				from CTHD 
				where HOADON.sohd=CTHD.sohd and CTHD.masp=SANPHAM.masp) )
-- 3.19
SELECT A.SOHD ,SOLAN
FROM HOADON A JOIN (SELECT MIN(SL) SOLAN 
					FROM HOADON HD JOIN (
							SELECT HOADON.SOHD , COUNT(*) SL
							FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP =CTHD.MASP 
							WHERE NUOCSX = 'Singapore' AND YEAR(NGHD) = 2006 
							GROUP BY HOADON.SOHD) TABLE1 
								ON TABLE1.SOHD = HD.SOHD 
					) TABLE2 
						ON A.SOHD = TABLE2.SOHD
					

SELECT  COUNT (*) AS SOLANMUA 
FROM (CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD ) JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE NUOCSX = 'Singapore'  AND YEAR(NGHD) = 2006
-- 3.20
SELECT COUNT(*) AS SOHOADONKHONGPHAIDOTHANHVIENMUA
FROM HOADON
WHERE MAKH IS NULL
-- 3.21 *
SELECT COUNT(DISTINCT MASP)
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGHD) = 2006
-- 3.22
SELECT MIN(TRIGIA) AS THAPNHAT , MAX (TRIGIA) AS CAONHAT
FROM HOADON
-- 3.23
SELECT AVG(TRIGIA) AS TRUNGBINH2006
FROM HOADON
WHERE YEAR(NGHD) ='2006'
-- 3.24 
SELECT SUM(TRIGIA) AS DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
-- 3.25
SELECT SOHD
FROM HOADON
WHERE TRIGIA= (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR(NGHD) =2006 )
-- 3.26
SELECT HOTEN
FROM HOADON JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
WHERE TRIGIA = (SELECT MAX(TRIGIA) FROM HOADON WHERE YEAR (NGHD)=2006)

-- 3.27
SELECT TOP 3 MAKH , HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC
-- 3.28
SELECT MASP ,TENSP
FROM SANPHAM
WHERE GIA IN (
	SELECT TOP 3 GIA
	FROM SANPHAM
	ORDER BY GIA DESC)

-- 3.29
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan' AND GIA IN (
						SELECT TOP 3 GIA 
						FROM SANPHAM 
						ORDER BY GIA DESC )
-- 3.30
SELECT MASP , TENSP
FROM SANPHAM
WHERE NUOCSX ='Trung Quoc' AND GIA IN (
									SELECT TOP 3 GIA
									FROM SANPHAM
									WHERE NUOCSX ='Trung Quoc'
									ORDER BY GIA DESC )
-- 3.31

-- 3.32
SELECT COUNT (*) AS SOSP
FROM SANPHAM
WHERE NUOCSX='Trung Quoc'
-- 3.33 
SELECT NUOCSX , COUNT (*) AS SOSP
FROM SANPHAM
GROUP BY NUOCSX 
-- 3.34
SELECT NUOCSX , MAX(GIA) AS GIACAONHAT , MIN(GIA) AS GIATHAPNHAT , AVG(GIA) AS GIATB
FROM SANPHAM
GROUP BY NUOCSX
-- 3.35
SELECT NGHD , SUM(TRIGIA) AS DOANHTHU
FROM HOADON
GROUP BY NGHD

-- 3.36
SELECT MASP , SUM(SL) AS SL
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE MONTH (NGHD) = 10 AND YEAR (NGHD) = 2006
GROUP BY MASP
-- 3.37
SELECT MONTH(NGHD) AS THANG , SUM(TRIGIA) AS TONGDOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
-- 3.38
SELECT SOHD 
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) > 3
-- 3.39
SELECT SOHD 
FROM CTHD JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE NUOCSX ='Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3
-- 3.40
SELECT TOP 1 KHACHHANG.MAKH
FROM HOADON JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH , HOTEN
ORDER BY COUNT(*) DESC

-- 3.41
SELECT TOP 1 MONTH(NGHD) AS THANG 
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC
-- 3.42
SELECT MASP 
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR (NGHD) = 2006
GROUP BY MASP
ORDER BY SUM(SL) ASC
-- 3.43
SELECT NUOCSX , MASP , TENSP 
FROM SANPHAM
GROUP BY NUOCSX , MASP ,TENSP 
ORDER BY MAX(GIA) DESC
-- 3.44
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) > 2
-- 3.45
SELECT TOP 1 MAKH ,HOTEN 
FROM (
		SELECT TOP 10 KHACHHANG.MAKH , KHACHHANG.HOTEN , COUNT(HOADON.MAKH) AS SL
		FROM  KHACHHANG JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
		GROUP BY KHACHHANG.MAKH , KHACHHANG.DOANHSO , KHACHHANG.HOTEN
		ORDER BY KHACHHANG.DOANHSO DESC
		) KH
ORDER BY SL DESC

